# Generated by Django 3.0.4 on 2020-04-03 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fudr', '0002_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='image',
        ),
    ]
